name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Deploy Infra
        run: |
          cd infra
          cdktf deploy --auto-approve

  deploy-app:
    runs-on: ubuntu-latest
    needs: deploy-infra
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push Docker Image
        run: |
          cd app
          docker build -t myrepo/myapp:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push myrepo/myapp:latest
      - name: Deploy to EKS
        run: |
          kubectl apply -f app/deployment.yaml
          kubectl apply -f app/service.yaml
